runtime: python39

instance_class: F2

env_variables:
  SECRET_KEY: "8f7c95ef3e6507753ea648c4659c36f1"
  DEBUG: "False"  # It's recommended to turn off debug mode in production
  DATABASE_URL: "postgresql://infyulabs:infyulabs123@/sensors?host=/cloudsql/sensor-reading-404008:asia-south1:sensor"
  SQLALCHEMY_TRACK_MODIFICATIONS: "False"
  # Add other environment variables as needed

beta_settings:
  cloud_sql_instances: sensor-reading-404008:asia-south1:sensor

entrypoint: gunicorn -b :$PORT app:app
